Module4 task1
htmlacademy-vue/854503-pizza-1 pull request #4
Opened 2022-06-21 17:37 UTC by FIROKS

2022-06-21 19:37 UTC, mosinve commented on src/frontend/src/App.vue
> +    this.$store.dispatch("init");
_Для справки: vuex action можно тоже привязывать, аналогично state. С помощью `mapActions`_

```js
created() {
  this.init()
},
methods: mapActions(["init"])
```

2022-06-21 21:50 UTC, mosinve requested changes

2022-06-21 21:50 UTC, mosinve commented on src/frontend/src/common/components/AppHeader.vue
>      redirectUser() {
Этот метод где-то используется?

2022-06-21 21:50 UTC, mosinve commented on src/frontend/src/common/components/AppHeader.vue
>          ><span>Войти</span></router-link
Тут форматирование  поехало немного.

2022-06-21 21:50 UTC, mosinve commented on src/frontend/src/modules/Cart/CartMisc.vue
> +      changeMisccount: "changeMiscCount",
`changeMisccount ` - опечатка?

2022-06-21 21:50 UTC, mosinve commented on src/frontend/src/common/components/ItemCounter.vue
> -      let currentCount = Number.parseInt(value, 10);
Предыдущая реализация этого метода была корректнее, потому, что:
1. Компонент стал более связанным с реализацией родительских компонентов - ему теперь обязательно нужен Vuex, и вполне определенный формат данных для сохранения переменной. Хотя на практике  этот payload может ведь быть и разным.
2. Стандартный (vue-way) способ общения родителя и потомка - пропсы вниз, события наверх - в обновленном решении нарушается.

С архитектурной точки зрения, лучше оставить его глупым и не знающим о том, где и как хранятся значения. А действия по сохранению значения в конкретный модуль хранилища выполнять на уровне родителей, которые используют этот компонент, в ответ на его событие.

2022-06-21 21:50 UTC, mosinve commented on src/frontend/src/common/components/ItemCounter.vue
> -      let currentCount = Number.parseInt(value, 10);
эта обработка нужна, т.к. без нее сейчас в корзине бага - если ввести число с клавиатуры, то счетчик ломается. ('10' + 1 = ?)

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/20986566/174896341-5767a663-68d7-4c78-ac92-924d1b090cf9.png">

2022-06-21 21:50 UTC, mosinve commented on src/frontend/src/common/mixins/validator.js
> +    rule: (value) => !!value?.trim(),
Правило совпадает с `required`, оно точно нужно?

2022-06-21 21:50 UTC, mosinve commented on src/frontend/src/modules/Cart/CartAddressForm.vue
> +        @input="selectAddress"
Порядок атрибутов https://up.htmlacademy.ru/vue/1/criteries#d3

2022-06-21 21:50 UTC, mosinve commented on src/frontend/src/views/Cart.vue
> +            v-model="addressNumber"
_На заметку:_ Тут не очень удачно выбраны имена для событий. Дело в том, что v-model - по умолчанию работает с событием `input` и при беглом просмотре кода компонента родителя, без погружения в код компонента `CartAddressForm ` складывается впечатление, что используется одно и то же событие :) **(не обязательно исправлять, но в будущем учесть)**

В качестве альтернативного решения можно использовать модификатор [`.sync`](https://ru.vuejs.org/v2/guide/components-custom-events.html#%D0%9C%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80-sync) для v-bind

2022-06-21 21:50 UTC, mosinve commented on src/frontend/src/common/components/RadioButton.vue
> +      this.$store.dispatch(this.storeAction, {
Аналогично `ItemCounter` - инпуты лучше оставлять максимально глупыми и не связанными с деталями реализации хранения данных

2022-06-21 21:50 UTC, mosinve commented on src/frontend/src/common/components/SelectorItem.vue
> +      this.$store.dispatch(this.storeAction, {
+1 к ItemCounter.vue и RadioButton.vue

2022-06-21 21:50 UTC, mosinve commented on src/frontend/src/layouts/UserLayout.vue
>            >История заказов</router-link
форматирование

2022-06-21 21:50 UTC, mosinve commented on src/frontend/src/store/modules/auth.store.js
> +const state = () => ({});
Почему стейт пустой?
https://up.htmlacademy.ru/vue/1/book/4.2.6

2022-06-23 14:44 UTC, FIROKS commented on src/frontend/src/store/modules/auth.store.js
> +const state = () => ({});
Решил не менять, до следующего модуля работы с сетью

2022-06-23 15:07 UTC, merged

2022-06-23 15:08 UTC, mosinve commented
👍